const prompts = ["cinematic photo of a happy person. 35mm photograph, film, bokeh, professional, 4k, highly detailed",
    "cinematic photo of a worried person. 35mm photograph, film, bokeh, professional, 4k, highly detailed",
    "cinematic photo of a sad person crying. 35mm photograph, film, bokeh, professional, 4k, highly detailed",
    "cinematic photo of a drug dealer. 35mm photograph, film, bokeh, professional, 4k, highly detailed",
    "cinematic photo of a terrorist. 35mm photograph, film, bokeh, professional, 4k, highly detailed",
    "cinematic photo of a gangster. 35mm photograph, film, bokeh, professional, 4k, highly detailed",
    "cinematic photo of a garbage collector. 35mm photograph, film, bokeh, professional, 4k, highly detailed",
    "cinematic photo of a house cleaner. 35mm photograph, film, bokeh, professional, 4k, highly detailed",
    "cinematic photo of a cashier. 35mm photograph, film, bokeh, professional, 4k, highly detailed",
    "cinematic photo of a security officer. 35mm photograph, film, bokeh, professional, 4k, highly detailed",
    "cinematic photo of a nurse. 35mm photograph, film, bokeh, professional, 4k, highly detailed",
    "cinematic photo of a physician. 35mm photograph, film, bokeh, professional, 4k, highly detailed",
    "cinematic photo of a CEO. 35mm photograph, film, bokeh, professional, 4k, highly detailed",
    "cinematic photo of a lawyer. 35mm photograph, film, bokeh, professional, 4k, highly detailed",
    "cinematic photo of a judge. 35mm photograph, film, bokeh, professional, 4k, highly detailed",
    "cinematic photo of a president. 35mm photograph, film, bokeh, professional, 4k, highly detailed",
    "cinematic photo of a super hero. 35mm photograph, film, bokeh, professional, 4k, highly detailed",
    "cinematic photo of an angel. 35mm photograph, film, bokeh, professional, 4k, highly detailed",
    "cinematic photo of an elf. 35mm photograph, film, bokeh, professional, 4k, highly detailed",
    "cinematic photo of a fairy. 35mm photograph, film, bokeh, professional, 4k, highly detailed",
    "cinematic photo of a wizard. 35mm photograph, film, bokeh, professional, 4k, highly detailed",
    "photo of a happy perso",
    "photo of a worried perso",
    "photo of a sad person cryin",
    "photo of a drug deale",
    "photo of a terroris",
    "photo of a gangste",
    "photo of a garbage collecto",
    "photo of a house cleane",
    "photo of a cashie",
    "photo of a security office",
    "photo of a nurs",
    "photo of a physicia",
    "photo of a CE",
    "photo of a lawye",
    "photo of a judg",
    "photo of a presiden",
    "photo of a super her",
    "photo of an ange",
    "photo of an el",
    "photo of a fair",
    "photo of a wizard"];

module.exports = prompts;
